<?php

use App\Fournisseur;
use Illuminate\Database\Seeder;

class FournisseurSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      Fournisseur::insert([
        [ "Nom" => "RHUNAO",  "Cp" => "87070", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "GAILLIARD",  "Cp" => "36632", "Ville" => "Lyon", "Pays" => "France"],
        [ "Nom" => "JULES TOURNIER & FILS",  "Cp" => "40601", "Ville" => "Lille", "Pays" => "France"],
        [ "Nom" => "LAINIERE DE PICARDIE",  "Cp" => "51499", "Ville" => "Montreal", "Pays" => "Canada"],
        [ "Nom" => "PEUCELLE & FLORIN",  "Cp" => "15789", "Ville" => "Montreal", "Pays" => "Canada"],
        [ "Nom" => "ALPEX INSIDE",  "Cp" => "81238", "Ville" => "Berlin", "Pays" => "Allemagne"],
        [ "Nom" => "B.T.A.",  "Cp" => "47094", "Ville" => "Montreal", "Pays" => "Canada"],
        [ "Nom" => "BAUDCHON ROUBANNE",  "Cp" => "91850", "Ville" => "Toronto", "Pays" => "Canada"],
        [ "Nom" => "BEL MAILLE",  "Cp" => "51079", "Ville" => "Paris", "Pays" => "France"],
        [ "Nom" => "BELINAC",  "Cp" => "67875", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "BERGEZ TEXTILES",  "Cp" => "94859", "Ville" => "Nantes", "Pays" => "France"],
        [ "Nom" => "BILLON TECHNIC",  "Cp" => "75368", "Ville" => "Berlin", "Pays" => "Allemagne"],
        [ "Nom" => "BUGIS TISSUS TECHNIQUES",  "Cp" => "40272", "Ville" => "Liège", "Pays" => "Belgique"],
        [ "Nom" => "CARRINGTON",  "Cp" => "78586", "Ville" => "Toronto", "Pays" => "Canada"],
        [ "Nom" => "CARRINGTON/OMC",  "Cp" => "44156", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "CHASTEX MAILLE",  "Cp" => "66975", "Ville" => "Brussels", "Pays" => "Belgique"],
        [ "Nom" => "CHATELARD",  "Cp" => "41742", "Ville" => "Brussels", "Pays" => "Belgique"],
        [ "Nom" => "CIEVA",  "Cp" => "98093", "Ville" => "Montreal", "Pays" => "Canada"],
        [ "Nom" => "COATING APPLICATIONS GROUP",  "Cp" => "88752", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "COLAMTISS SA",  "Cp" => "39728", "Ville" => "Brussels", "Pays" => "Belgique"],
        [ "Nom" => "CONCORDIA",  "Cp" => "61017", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "DICKSON",  "Cp" => "48965", "Ville" => "Liège", "Pays" => "Belgique"],
        [ "Nom" => "DORMAILLE",  "Cp" => "94432", "Ville" => "Berlin", "Pays" => "Allemagne"],
        [ "Nom" => "DRAI TISSUS",  "Cp" => "42030", "Ville" => "Montreal", "Pays" => "Canada"],
        [ "Nom" => "EPM",  "Cp" => "77454", "Ville" => "Liège", "Pays" => "Belgique"],
        [ "Nom" => "ERTEC",  "Cp" => "40515", "Ville" => "Toronto", "Pays" => "Canada"],
        [ "Nom" => "EUROPROTECT",  "Cp" => "81149", "Ville" => "Paris", "Pays" => "France"],
        [ "Nom" => "FRANFITEX",  "Cp" => "86262", "Ville" => "Toronto", "Pays" => "Canada"],
        [ "Nom" => "GILBERT PRODUCTION",  "Cp" => "11721", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "HT CONCEPT",  "Cp" => "57723", "Ville" => "Toronto", "Pays" => "Canada"],
        [ "Nom" => "KLOPMAN International",  "Cp" => "64555", "Ville" => "Montreal", "Pays" => "Canada"],
        [ "Nom" => "LAUFFENMUHLE",  "Cp" => "13051", "Ville" => "Berlin", "Pays" => "Allemagne"],
        [ "Nom" => "MARFON TEXTIL",  "Cp" => "89959", "Ville" => "Berlin", "Pays" => "Allemagne"],
        [ "Nom" => "MERMET VERNE ET CLET",  "Cp" => "70573", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "NOIRET TISSU",  "Cp" => "33905", "Ville" => "Paris", "Pays" => "France"],
        [ "Nom" => "PELTEX",  "Cp" => "65310", "Ville" => "Bordeaux", "Pays" => "France"],
        [ "Nom" => "PLASTIBERT ET CIE",  "Cp" => "92890", "Ville" => "Berlin", "Pays" => "Allemagne"],
        [ "Nom" => "PROLINE Textile",  "Cp" => "86387", "Ville" => "Liège", "Pays" => "Belgique"],
        [ "Nom" => "RIVERTEX TECHNICAL FABRICS",  "Cp" => "64724", "Ville" => "Toronto", "Pays" => "Canada"],
        [ "Nom" => "ROUDIERE",  "Cp" => "27400", "Ville" => "Brussels", "Pays" => "Belgique"],
        [ "Nom" => "TDV Industries",  "Cp" => "71654", "Ville" => "Montreal", "Pays" => "Canada"],
        [ "Nom" => "TEN CATE PROTECT France",  "Cp" => "88599", "Ville" => "Liège", "Pays" => "Belgique"],
        [ "Nom" => "THOVISTE SA",  "Cp" => "30983", "Ville" => "Liège", "Pays" => "Belgique"],
        [ "Nom" => "TISSAGES DE L'AIGLE",  "Cp" => "21408", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "TOOTAL FABRICS",  "Cp" => "16405", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "UTEXBEL",  "Cp" => "33078", "Ville" => "Lille", "Pays" => "France"],
        [ "Nom" => "VERNE ET CLET",  "Cp" => "56005", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "2VL TEXTILE",  "Cp" => "16596", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "3 M",  "Cp" => "98657", "Ville" => "Lille", "Pays" => "France"],
        [ "Nom" => "ALBERT SA",  "Cp" => "11873", "Ville" => "Toronto", "Pays" => "Canada"],
        [ "Nom" => "ALPHA BIAIS",  "Cp" => "29567", "Ville" => "Berlin", "Pays" => "Allemagne"],
        [ "Nom" => "APLIX",  "Cp" => "49389", "Ville" => "Toronto", "Pays" => "Canada"],
        [ "Nom" => "AUTOADESIVI",  "Cp" => "39232", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "AVONS",  "Cp" => "15609", "Ville" => "Montreal", "Pays" => "Canada"],
        [ "Nom" => "BATTENTIER S.A",  "Cp" => "99076", "Ville" => "Brussels", "Pays" => "Belgique"],
        [ "Nom" => "BIEZE STORK (SEPCO)",  "Cp" => "68384", "Ville" => "Liège", "Pays" => "Belgique"],
        [ "Nom" => "BIMECO Garnhandel GmbH & Co.",  "Cp" => "28670", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "BOUTONS KOCHER SA",  "Cp" => "26770", "Ville" => "Lyon", "Pays" => "France"],
        [ "Nom" => "CARTONNERIE TONNELLIER",  "Cp" => "80590", "Ville" => "Lille", "Pays" => "France"],
        [ "Nom" => "COATS FRANCE",  "Cp" => "70239", "Ville" => "Brussels", "Pays" => "Belgique"],
        [ "Nom" => "COINDEROUX",  "Cp" => "86757", "Ville" => "Berlin", "Pays" => "Allemagne"],
        [ "Nom" => "COUSIN FILTERIE",  "Cp" => "86513", "Ville" => "Liège", "Pays" => "Belgique"],
        [ "Nom" => "CREPIN PETIT",  "Cp" => "97896", "Ville" => "Montreal", "Pays" => "Canada"],
        [ "Nom" => "DESCHAMPS IMPRIMERIE",  "Cp" => "76773", "Ville" => "Berlin", "Pays" => "Allemagne"],
        [ "Nom" => "DESEMAC",  "Cp" => "64595", "Ville" => "Paris", "Pays" => "France"],
        [ "Nom" => "DIATEX",  "Cp" => "54807", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "DIFAC",  "Cp" => "42586", "Ville" => "Lille", "Pays" => "France"],
        [ "Nom" => "DMC FILS",  "Cp" => "24114", "Ville" => "Nantes", "Pays" => "France"],
        [ "Nom" => "DORLET",  "Cp" => "91738", "Ville" => "Montreal", "Pays" => "Canada"],
        [ "Nom" => "ECLAIR PRYM FRANCE",  "Cp" => "62349", "Ville" => "Toronto", "Pays" => "Canada"],
        [ "Nom" => "EPAU-NOVA",  "Cp" => "43061", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "FIBERLIVE",  "Cp" => "25474", "Ville" => "Toronto", "Pays" => "Canada"],
        [ "Nom" => "IMATEL",  "Cp" => "78075", "Ville" => "Lyon", "Pays" => "France"],
        [ "Nom" => "JABOULEY",  "Cp" => "15837", "Ville" => "Berlin", "Pays" => "Allemagne"],
        [ "Nom" => "KORTEKS",  "Cp" => "54634", "Ville" => "Paris", "Pays" => "France"],
        [ "Nom" => "KROKO",  "Cp" => "21385", "Ville" => "Marseille", "Pays" => "France"],
        [ "Nom" => "LAHU SIMON",  "Cp" => "63739", "Ville" => "Montreal", "Pays" => "Canada"],
        [ "Nom" => "MAXEL",  "Cp" => "79586", "Ville" => "Brussels", "Pays" => "Belgique"],
        [ "Nom" => "MICEL",  "Cp" => "39740", "Ville" => "Liège", "Pays" => "Belgique"],
        [ "Nom" => "MORITO",  "Cp" => "34858", "Ville" => "Berlin", "Pays" => "Allemagne"],
        [ "Nom" => "MULTISAC",  "Cp" => "20964", "Ville" => "Marseille", "Pays" => "France"],
        [ "Nom" => "NEYRET FRERES",  "Cp" => "70345", "Ville" => "Toronto", "Pays" => "Canada"],
        [ "Nom" => "PLOVIER ETS.",  "Cp" => "29671", "Ville" => "Montreal", "Pays" => "Canada"],
        [ "Nom" => "POLYMARK SERVICE",  "Cp" => "75366", "Ville" => "Brussels", "Pays" => "Belgique"],
        [ "Nom" => "REFLEXITE",  "Cp" => "76149", "Ville" => "Toronto", "Pays" => "Canada"],
        [ "Nom" => "ROTTA",  "Cp" => "20724", "Ville" => "Montreal", "Pays" => "Canada"],
        [ "Nom" => "RUBANS GALLANT",  "Cp" => "88253", "Ville" => "Toronto", "Pays" => "Canada"],
        [ "Nom" => "SAMPC",  "Cp" => "49507", "Ville" => "Bordeaux", "Pays" => "France"],
        [ "Nom" => "SCHAEFFER",  "Cp" => "49760", "Ville" => "Liège", "Pays" => "Belgique"],
        [ "Nom" => "SCOVILL",  "Cp" => "26177", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "SCOVILL EUROPE SA",  "Cp" => "36898", "Ville" => "Berlin", "Pays" => "Allemagne"],
        [ "Nom" => "SEPCO TEXTILES",  "Cp" => "76656", "Ville" => "Berlin", "Pays" => "Allemagne"],
        [ "Nom" => "SERIPRESS",  "Cp" => "45251", "Ville" => "Berlin", "Pays" => "Allemagne"],
        [ "Nom" => "SEROLATEX",  "Cp" => "78822", "Ville" => "Paris", "Pays" => "France"],
        [ "Nom" => "SMB BORD COTE",  "Cp" => "24864", "Ville" => "Marseille", "Pays" => "France"],
        [ "Nom" => "T 2 S",  "Cp" => "19811", "Ville" => "Lille", "Pays" => "France"],
        [ "Nom" => "TEXPRO SPA",  "Cp" => "69504", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "TEXTILES EN BIAIS",  "Cp" => "41108", "Ville" => "Liège", "Pays" => "Belgique"],
        [ "Nom" => "THERMO CODE SYSTEM",  "Cp" => "76629", "Ville" => "Berlin", "Pays" => "Allemagne"],
        [ "Nom" => "TISSAGE J. JURINE",  "Cp" => "40661", "Ville" => "Brussels", "Pays" => "Belgique"],
        [ "Nom" => "TOPKAPI",  "Cp" => "14592", "Ville" => "Brussels", "Pays" => "Belgique"],
        [ "Nom" => "TURQUAIS",  "Cp" => "87714", "Ville" => "Liège", "Pays" => "Belgique"],
        [ "Nom" => "VETEX",  "Cp" => "73985", "Ville" => "Berlin", "Pays" => "Allemagne"],
        [ "Nom" => "WANTOLI",  "Cp" => "33572", "Ville" => "Toronto", "Pays" => "Canada"],
        [ "Nom" => "YOSHIDA Y.K.K.",  "Cp" => "50271", "Ville" => "Toronto", "Pays" => "Canada"],
        [ "Nom" => "A.P.E.A.H",  "Cp" => "77171", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "AAMIC",  "Cp" => "56982", "Ville" => "Berlin", "Pays" => "Allemagne"],
        [ "Nom" => "AFNOR",  "Cp" => "95115", "Ville" => "Brussels", "Pays" => "Belgique"],
        [ "Nom" => "AUDIT INTERNATIONAL",  "Cp" => "68311", "Ville" => "Liège", "Pays" => "Belgique"],
        [ "Nom" => "EMBASSY TOURS",  "Cp" => "57277", "Ville" => "Montreal", "Pays" => "Canada"],
        [ "Nom" => "GRAVELEAU",  "Cp" => "17278", "Ville" => "Liège", "Pays" => "Belgique"],
        [ "Nom" => "INSTITUT TEXTILE DE FRANCE",  "Cp" => "70252", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "J.B.M.",  "Cp" => "50568", "Ville" => "Brussels", "Pays" => "Belgique"],
        [ "Nom" => "JCM",  "Cp" => "60502", "Ville" => "Lyon", "Pays" => "France"],
        [ "Nom" => "RIVOIRE",  "Cp" => "26370", "Ville" => "Brussels", "Pays" => "Belgique"],
        [ "Nom" => "AR'IMPRESSION",  "Cp" => "68799", "Ville" => "Berlin", "Pays" => "Allemagne"],
        [ "Nom" => "ATS",  "Cp" => "91350", "Ville" => "Paris", "Pays" => "France"],
        [ "Nom" => "B.G.S BRODERIE",  "Cp" => "85250", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "B.G.S SERIGRAPHIE",  "Cp" => "80171", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "FLOCKAGE DU CENTRE",  "Cp" => "75841", "Ville" => "Montreal", "Pays" => "Canada"],
        [ "Nom" => "TIDALIA",  "Cp" => "35196", "Ville" => "Liège", "Pays" => "Belgique"],
        [ "Nom" => "TRALONGO A.B.A",  "Cp" => "32154", "Ville" => "Berlin", "Pays" => "Allemagne"],
        [ "Nom" => "AFCO",  "Cp" => "59489", "Ville" => "Montreal", "Pays" => "Canada"],
        [ "Nom" => "AMTS",  "Cp" => "16292", "Ville" => "Brussels", "Pays" => "Belgique"],
        [ "Nom" => "BEKALTEX",  "Cp" => "37861", "Ville" => "Brussels", "Pays" => "Belgique"],
        [ "Nom" => "BENCO Confection",  "Cp" => "34637", "Ville" => "Lille", "Pays" => "France"],
        [ "Nom" => "CCM",  "Cp" => "14088", "Ville" => "Nantes", "Pays" => "France"],
        [ "Nom" => "CMT International",  "Cp" => "37959", "Ville" => "Berlin", "Pays" => "Allemagne"],
        [ "Nom" => "COVEP",  "Cp" => "62926", "Ville" => "Brussels", "Pays" => "Belgique"],
        [ "Nom" => "CROSS ROADS",  "Cp" => "13455", "Ville" => "Liège", "Pays" => "Belgique"],
        [ "Nom" => "DOMPIERRE CONFECTION",  "Cp" => "95697", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "DUTEX",  "Cp" => "73109", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "EUROCONFEX",  "Cp" => "21169", "Ville" => "Liège", "Pays" => "Belgique"],
        [ "Nom" => "FELLA CONFECTION",  "Cp" => "35310", "Ville" => "Paris", "Pays" => "France"],
        [ "Nom" => "FILATURE DE PARTHENAY",  "Cp" => "88623", "Ville" => "Berlin", "Pays" => "Allemagne"],
        [ "Nom" => "FILATURES DE CHENIMENIL",  "Cp" => "67434", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "FRANCE TEINTURE",  "Cp" => "29910", "Ville" => "Montreal", "Pays" => "Canada"],
        [ "Nom" => "HADADRATEX",  "Cp" => "30556", "Ville" => "Paris", "Pays" => "France"],
        [ "Nom" => "JERCO",  "Cp" => "36956", "Ville" => "Brussels", "Pays" => "Belgique"],
        [ "Nom" => "MATEL TEINTURERIE",  "Cp" => "45905", "Ville" => "Lyon", "Pays" => "France"],
        [ "Nom" => "MEDTEX Confection",  "Cp" => "52682", "Ville" => "Berlin", "Pays" => "Allemagne"],
        [ "Nom" => "MGM",  "Cp" => "29759", "Ville" => "Montreal", "Pays" => "Canada"],
        [ "Nom" => "BFH",  "Cp" => "50665", "Ville" => "Liège", "Pays" => "Belgique"],
        [ "Nom" => "RONIMAN",  "Cp" => "87568", "Ville" => "Brussels", "Pays" => "Belgique"],
        [ "Nom" => "SOFAC",  "Cp" => "65843", "Ville" => "Lille", "Pays" => "France"],
        [ "Nom" => "SOMATEX",  "Cp" => "79407", "Ville" => "Lyon", "Pays" => "France"],
        [ "Nom" => "SOTAP CAROL",  "Cp" => "28923", "Ville" => "Marseille", "Pays" => "France"],
        [ "Nom" => "SOTUVET",  "Cp" => "25774", "Ville" => "Montreal", "Pays" => "Canada"],
        [ "Nom" => "SPORTEX",  "Cp" => "95125", "Ville" => "Lille", "Pays" => "France"],
        [ "Nom" => "SYLVESTRE CONFECTION",  "Cp" => "38739", "Ville" => "Nantes", "Pays" => "France"],
        [ "Nom" => "TAD",  "Cp" => "23426", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "TCI TRICOTAGE CIRCUL INDUST",  "Cp" => "11328", "Ville" => "Brussels", "Pays" => "Belgique"],
        [ "Nom" => "TEINTURERIE DE MATEL",  "Cp" => "49038", "Ville" => "Nantes", "Pays" => "France"],
        [ "Nom" => "TEINTURERIE DRUHEN",  "Cp" => "20682", "Ville" => "Montreal", "Pays" => "Canada"],
        [ "Nom" => "TEINTURERIE MOREUIL",  "Cp" => "64124", "Ville" => "Liège", "Pays" => "Belgique"],
        [ "Nom" => "THINON D. TRICOTAGE",  "Cp" => "59598", "Ville" => "Lyon", "Pays" => "France"],
        [ "Nom" => "TRICOTAGE DE CLARY",  "Cp" => "60948", "Ville" => "Liège", "Pays" => "Belgique"],
        [ "Nom" => "TRICOTAGE DE L'ENCLOS",  "Cp" => "95651", "Ville" => "Paris", "Pays" => "France"],
        [ "Nom" => "TRICOTAGE TOULOUSAIN",  "Cp" => "90370", "Ville" => "Bordeaux", "Pays" => "France"],
        [ "Nom" => "TRICOTAGES DUCHAMP",  "Cp" => "40800", "Ville" => "Brussels", "Pays" => "Belgique"],
        [ "Nom" => "exapaq",  "Cp" => "63429", "Ville" => "Liège", "Pays" => "Belgique"],
        [ "Nom" => "MORY TEAM",  "Cp" => "10086", "Ville" => "Brussels", "Pays" => "Belgique"],
        [ "Nom" => "JOYAU SCHENKER",  "Cp" => "65779", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "MANUPAL",  "Cp" => "97361", "Ville" => "Montreal", "Pays" => "Canada"],
        [ "Nom" => "BROD TUNIS SARL",  "Cp" => "93712", "Ville" => "Toronto", "Pays" => "Canada"],
        [ "Nom" => "SVI",  "Cp" => "53292", "Ville" => "Nantes", "Pays" => "France"],
        [ "Nom" => "WORKWEAR",  "Cp" => "15131", "Ville" => "Brussels", "Pays" => "Belgique"],
        [ "Nom" => "JOD FACTORY",  "Cp" => "80424", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "SNS",  "Cp" => "26637", "Ville" => "Montreal", "Pays" => "Canada"],
        [ "Nom" => "CHALETX",  "Cp" => "46840", "Ville" => "Marseille", "Pays" => "France"],
        [ "Nom" => "AJ GROUP",  "Cp" => "84501", "Ville" => "Toronto", "Pays" => "Canada"],
        [ "Nom" => "RHUNAO",  "Cp" => "92567", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "GAILLIARD",  "Cp" => "64349", "Ville" => "Paris", "Pays" => "France"],
        [ "Nom" => "JULES TOURNIER & FILS",  "Cp" => "56714", "Ville" => "Toronto", "Pays" => "Canada"],
        [ "Nom" => "LAINIERE DE PICARDIE",  "Cp" => "13701", "Ville" => "Marseille", "Pays" => "France"],
        [ "Nom" => "PEUCELLE & FLORIN",  "Cp" => "28612", "Ville" => "Berlin", "Pays" => "Allemagne"],
        [ "Nom" => "ALPEX INSIDE",  "Cp" => "74773", "Ville" => "Liège", "Pays" => "Belgique"],
        [ "Nom" => "B.T.A.",  "Cp" => "94072", "Ville" => "Berlin", "Pays" => "Allemagne"],
        [ "Nom" => "BAUDCHON ROUBANNE",  "Cp" => "13820", "Ville" => "Montreal", "Pays" => "Canada"],
        [ "Nom" => "BEL MAILLE",  "Cp" => "64770", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "BELINAC",  "Cp" => "24399", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "BERGEZ TEXTILES",  "Cp" => "13567", "Ville" => "Toronto", "Pays" => "Canada"],
        [ "Nom" => "BILLON TECHNIC",  "Cp" => "17665", "Ville" => "Brussels", "Pays" => "Belgique"],
        [ "Nom" => "BUGIS TISSUS TECHNIQUES",  "Cp" => "88066", "Ville" => "Toronto", "Pays" => "Canada"],
        [ "Nom" => "CARRINGTON",  "Cp" => "56671", "Ville" => "Liège", "Pays" => "Belgique"],
        [ "Nom" => "CARRINGTON/OMC",  "Cp" => "18479", "Ville" => "Nantes", "Pays" => "France"],
        [ "Nom" => "CHASTEX MAILLE",  "Cp" => "51221", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "CHATELARD",  "Cp" => "64924", "Ville" => "Toronto", "Pays" => "Canada"],
        [ "Nom" => "CIEVA",  "Cp" => "22647", "Ville" => "Brussels", "Pays" => "Belgique"],
        [ "Nom" => "COATING APPLICATIONS GROUP",  "Cp" => "83486", "Ville" => "Marseille", "Pays" => "France"],
        [ "Nom" => "COLAMTISS SA",  "Cp" => "30851", "Ville" => "Toronto", "Pays" => "Canada"],
        [ "Nom" => "CONCORDIA",  "Cp" => "29453", "Ville" => "Montreal", "Pays" => "Canada"],
        [ "Nom" => "DICKSON",  "Cp" => "33305", "Ville" => "Brussels", "Pays" => "Belgique"],
        [ "Nom" => "DORMAILLE",  "Cp" => "21337", "Ville" => "Liège", "Pays" => "Belgique"],
        [ "Nom" => "DRAI TISSUS",  "Cp" => "80944", "Ville" => "Liège", "Pays" => "Belgique"],
        [ "Nom" => "EPM",  "Cp" => "77407", "Ville" => "Toronto", "Pays" => "Canada"],
        [ "Nom" => "ERTEC",  "Cp" => "80366", "Ville" => "Liège", "Pays" => "Belgique"],
        [ "Nom" => "EUROPROTECT",  "Cp" => "38829", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "FRANFITEX",  "Cp" => "76725", "Ville" => "Bordeaux", "Pays" => "France"],
        [ "Nom" => "GILBERT PRODUCTION",  "Cp" => "14112", "Ville" => "Nantes", "Pays" => "France"],
        [ "Nom" => "HT CONCEPT",  "Cp" => "39079", "Ville" => "Bordeaux", "Pays" => "France"],
        [ "Nom" => "KLOPMAN International",  "Cp" => "25943", "Ville" => "Brussels", "Pays" => "Belgique"],
        [ "Nom" => "LAUFFENMUHLE",  "Cp" => "22771", "Ville" => "Bordeaux", "Pays" => "France"],
        [ "Nom" => "MARFON TEXTIL",  "Cp" => "83950", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "MERMET VERNE ET CLET",  "Cp" => "24455", "Ville" => "Toronto", "Pays" => "Canada"],
        [ "Nom" => "NOIRET TISSU",  "Cp" => "38332", "Ville" => "Brussels", "Pays" => "Belgique"],
        [ "Nom" => "PELTEX",  "Cp" => "53131", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "PLASTIBERT ET CIE",  "Cp" => "17943", "Ville" => "Lille", "Pays" => "France"],
        [ "Nom" => "PROLINE Textile",  "Cp" => "18785", "Ville" => "Toronto", "Pays" => "Canada"],
        [ "Nom" => "RIVERTEX TECHNICAL FABRICS",  "Cp" => "67143", "Ville" => "Lyon", "Pays" => "France"],
        [ "Nom" => "ROUDIERE",  "Cp" => "55271", "Ville" => "Toronto", "Pays" => "Canada"],
        [ "Nom" => "TDV Industries",  "Cp" => "56752", "Ville" => "Bordeaux", "Pays" => "France"],
        [ "Nom" => "TEN CATE PROTECT France",  "Cp" => "73385", "Ville" => "Marseille", "Pays" => "France"],
        [ "Nom" => "THOVISTE SA",  "Cp" => "67456", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "TISSAGES DE L'AIGLE",  "Cp" => "12459", "Ville" => "Liège", "Pays" => "Belgique"],
        [ "Nom" => "TOOTAL FABRICS",  "Cp" => "38062", "Ville" => "Toronto", "Pays" => "Canada"],
        [ "Nom" => "UTEXBEL",  "Cp" => "16513", "Ville" => "Brussels", "Pays" => "Belgique"],
        [ "Nom" => "VERNE ET CLET",  "Cp" => "23139", "Ville" => "Montreal", "Pays" => "Canada"],
        [ "Nom" => "2VL TEXTILE",  "Cp" => "92677", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "3 M",  "Cp" => "62302", "Ville" => "Bordeaux", "Pays" => "France"],
        [ "Nom" => "ALBERT SA",  "Cp" => "93635", "Ville" => "Montreal", "Pays" => "Canada"],
        [ "Nom" => "ALPHA BIAIS",  "Cp" => "11650", "Ville" => "Berlin", "Pays" => "Allemagne"],
        [ "Nom" => "APLIX",  "Cp" => "40007", "Ville" => "Berlin", "Pays" => "Allemagne"],
        [ "Nom" => "AUTOADESIVI",  "Cp" => "95269", "Ville" => "Brussels", "Pays" => "Belgique"],
        [ "Nom" => "AVONS",  "Cp" => "27983", "Ville" => "Berlin", "Pays" => "Allemagne"],
        [ "Nom" => "BATTENTIER S.A",  "Cp" => "32980", "Ville" => "Marseille", "Pays" => "France"],
        [ "Nom" => "BIEZE STORK (SEPCO)",  "Cp" => "54897", "Ville" => "Berlin", "Pays" => "Allemagne"],
        [ "Nom" => "BIMECO Garnhandel GmbH & Co.",  "Cp" => "66897", "Ville" => "Toronto", "Pays" => "Canada"],
        [ "Nom" => "BOUTONS KOCHER SA",  "Cp" => "52006", "Ville" => "Lille", "Pays" => "France"],
        [ "Nom" => "CARTONNERIE TONNELLIER",  "Cp" => "88006", "Ville" => "Toronto", "Pays" => "Canada"],
        [ "Nom" => "COATS FRANCE",  "Cp" => "52850", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "COINDEROUX",  "Cp" => "10267", "Ville" => "Montreal", "Pays" => "Canada"],
        [ "Nom" => "COUSIN FILTERIE",  "Cp" => "33852", "Ville" => "Montreal", "Pays" => "Canada"],
        [ "Nom" => "CREPIN PETIT",  "Cp" => "82527", "Ville" => "Berlin", "Pays" => "Allemagne"],
        [ "Nom" => "DESCHAMPS IMPRIMERIE",  "Cp" => "69431", "Ville" => "Brussels", "Pays" => "Belgique"],
        [ "Nom" => "DESEMAC",  "Cp" => "92256", "Ville" => "Berlin", "Pays" => "Allemagne"],
        [ "Nom" => "DIATEX",  "Cp" => "19216", "Ville" => "Lyon", "Pays" => "France"],
        [ "Nom" => "DIFAC",  "Cp" => "82555", "Ville" => "Nantes", "Pays" => "France"],
        [ "Nom" => "DMC FILS",  "Cp" => "15444", "Ville" => "Liège", "Pays" => "Belgique"],
        [ "Nom" => "DORLET",  "Cp" => "39008", "Ville" => "Toronto", "Pays" => "Canada"],
        [ "Nom" => "ECLAIR PRYM FRANCE",  "Cp" => "67978", "Ville" => "Toronto", "Pays" => "Canada"],
        [ "Nom" => "EPAU-NOVA",  "Cp" => "38706", "Ville" => "Berlin", "Pays" => "Allemagne"],
        [ "Nom" => "FIBERLIVE",  "Cp" => "48572", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "IMATEL",  "Cp" => "61985", "Ville" => "Berlin", "Pays" => "Allemagne"],
        [ "Nom" => "JABOULEY",  "Cp" => "12702", "Ville" => "Toronto", "Pays" => "Canada"],
        [ "Nom" => "KORTEKS",  "Cp" => "60989", "Ville" => "Lille", "Pays" => "France"],
        [ "Nom" => "KROKO",  "Cp" => "67432", "Ville" => "Liège", "Pays" => "Belgique"],
        [ "Nom" => "LAHU SIMON",  "Cp" => "33556", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "MAXEL",  "Cp" => "28738", "Ville" => "Lille", "Pays" => "France"],
        [ "Nom" => "MICEL",  "Cp" => "87883", "Ville" => "Marseille", "Pays" => "France"],
        [ "Nom" => "MORITO",  "Cp" => "88342", "Ville" => "Brussels", "Pays" => "Belgique"],
        [ "Nom" => "MULTISAC",  "Cp" => "19652", "Ville" => "Lyon", "Pays" => "France"],
        [ "Nom" => "NEYRET FRERES",  "Cp" => "47491", "Ville" => "Brussels", "Pays" => "Belgique"],
        [ "Nom" => "PLOVIER ETS.",  "Cp" => "41965", "Ville" => "Toronto", "Pays" => "Canada"],
        [ "Nom" => "POLYMARK SERVICE",  "Cp" => "10839", "Ville" => "Toronto", "Pays" => "Canada"],
        [ "Nom" => "REFLEXITE",  "Cp" => "22502", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "ROTTA",  "Cp" => "25973", "Ville" => "Lyon", "Pays" => "France"],
        [ "Nom" => "RUBANS GALLANT",  "Cp" => "99661", "Ville" => "Paris", "Pays" => "France"],
        [ "Nom" => "SAMPC",  "Cp" => "92161", "Ville" => "Liège", "Pays" => "Belgique"],
        [ "Nom" => "SCHAEFFER",  "Cp" => "49158", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "SCOVILL",  "Cp" => "24095", "Ville" => "Liège", "Pays" => "Belgique"],
        [ "Nom" => "SCOVILL EUROPE SA",  "Cp" => "60425", "Ville" => "Montreal", "Pays" => "Canada"],
        [ "Nom" => "SEPCO TEXTILES",  "Cp" => "12374", "Ville" => "Nantes", "Pays" => "France"],
        [ "Nom" => "SERIPRESS",  "Cp" => "89455", "Ville" => "Montreal", "Pays" => "Canada"],
        [ "Nom" => "SEROLATEX",  "Cp" => "76366", "Ville" => "Nantes", "Pays" => "France"],
        [ "Nom" => "SMB BORD COTE",  "Cp" => "74776", "Ville" => "Liège", "Pays" => "Belgique"],
        [ "Nom" => "T 2 S",  "Cp" => "64880", "Ville" => "Marseille", "Pays" => "France"],
        [ "Nom" => "TEXPRO SPA",  "Cp" => "42322", "Ville" => "Berlin", "Pays" => "Allemagne"],
        [ "Nom" => "TEXTILES EN BIAIS",  "Cp" => "39620", "Ville" => "Brussels", "Pays" => "Belgique"],
        [ "Nom" => "THERMO CODE SYSTEM",  "Cp" => "91281", "Ville" => "Lille", "Pays" => "France"],
        [ "Nom" => "TISSAGE J. JURINE",  "Cp" => "75015", "Ville" => "Berlin", "Pays" => "Allemagne"],
        [ "Nom" => "TOPKAPI",  "Cp" => "29803", "Ville" => "Lyon", "Pays" => "France"],
        [ "Nom" => "TURQUAIS",  "Cp" => "79330", "Ville" => "Brussels", "Pays" => "Belgique"],
        [ "Nom" => "VETEX",  "Cp" => "74786", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "WANTOLI",  "Cp" => "33665", "Ville" => "Paris", "Pays" => "France"],
        [ "Nom" => "YOSHIDA Y.K.K.",  "Cp" => "77252", "Ville" => "Montreal", "Pays" => "Canada"],
        [ "Nom" => "A.P.E.A.H",  "Cp" => "56359", "Ville" => "Lyon", "Pays" => "France"],
        [ "Nom" => "AAMIC",  "Cp" => "37940", "Ville" => "Toronto", "Pays" => "Canada"],
        [ "Nom" => "AFNOR",  "Cp" => "16900", "Ville" => "Berlin", "Pays" => "Allemagne"],
        [ "Nom" => "AUDIT INTERNATIONAL",  "Cp" => "31811", "Ville" => "Lyon", "Pays" => "France"],
        [ "Nom" => "EMBASSY TOURS",  "Cp" => "75057", "Ville" => "Berlin", "Pays" => "Allemagne"],
        [ "Nom" => "GRAVELEAU",  "Cp" => "65787", "Ville" => "Lyon", "Pays" => "France"],
        [ "Nom" => "INSTITUT TEXTILE DE FRANCE",  "Cp" => "21915", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "J.B.M.",  "Cp" => "28114", "Ville" => "Montreal", "Pays" => "Canada"],
        [ "Nom" => "JCM",  "Cp" => "44015", "Ville" => "Berlin", "Pays" => "Allemagne"],
        [ "Nom" => "RIVOIRE",  "Cp" => "15492", "Ville" => "Paris", "Pays" => "France"],
        [ "Nom" => "AR'IMPRESSION",  "Cp" => "36904", "Ville" => "Brussels", "Pays" => "Belgique"],
        [ "Nom" => "ATS",  "Cp" => "76460", "Ville" => "Berlin", "Pays" => "Allemagne"],
        [ "Nom" => "B.G.S BRODERIE",  "Cp" => "74437", "Ville" => "Berlin", "Pays" => "Allemagne"],
        [ "Nom" => "B.G.S SERIGRAPHIE",  "Cp" => "56487", "Ville" => "Toronto", "Pays" => "Canada"],
        [ "Nom" => "FLOCKAGE DU CENTRE",  "Cp" => "75848", "Ville" => "Toronto", "Pays" => "Canada"],
        [ "Nom" => "TIDALIA",  "Cp" => "87236", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "TRALONGO A.B.A",  "Cp" => "28482", "Ville" => "Berlin", "Pays" => "Allemagne"],
        [ "Nom" => "AFCO",  "Cp" => "42645", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "AMTS",  "Cp" => "46914", "Ville" => "Liège", "Pays" => "Belgique"],
        [ "Nom" => "BEKALTEX",  "Cp" => "21216", "Ville" => "Toronto", "Pays" => "Canada"],
        [ "Nom" => "BENCO Confection",  "Cp" => "11220", "Ville" => "Toronto", "Pays" => "Canada"],
        [ "Nom" => "CCM",  "Cp" => "75405", "Ville" => "Toronto", "Pays" => "Canada"],
        [ "Nom" => "CMT International",  "Cp" => "81387", "Ville" => "Montreal", "Pays" => "Canada"],
        [ "Nom" => "COVEP",  "Cp" => "39084", "Ville" => "Liège", "Pays" => "Belgique"],
        [ "Nom" => "CROSS ROADS",  "Cp" => "98141", "Ville" => "Montreal", "Pays" => "Canada"],
        [ "Nom" => "DOMPIERRE CONFECTION",  "Cp" => "60801", "Ville" => "Toronto", "Pays" => "Canada"],
        [ "Nom" => "DUTEX",  "Cp" => "68380", "Ville" => "Berlin", "Pays" => "Allemagne"],
        [ "Nom" => "EUROCONFEX",  "Cp" => "70405", "Ville" => "Liège", "Pays" => "Belgique"],
        [ "Nom" => "FELLA CONFECTION",  "Cp" => "27275", "Ville" => "Brussels", "Pays" => "Belgique"],
        [ "Nom" => "FILATURE DE PARTHENAY",  "Cp" => "86593", "Ville" => "Brussels", "Pays" => "Belgique"],
        [ "Nom" => "FILATURES DE CHENIMENIL",  "Cp" => "24247", "Ville" => "Lille", "Pays" => "France"],
        [ "Nom" => "FRANCE TEINTURE",  "Cp" => "57893", "Ville" => "Liège", "Pays" => "Belgique"],
        [ "Nom" => "HADADRATEX",  "Cp" => "44845", "Ville" => "Montreal", "Pays" => "Canada"],
        [ "Nom" => "JERCO",  "Cp" => "89169", "Ville" => "Berlin", "Pays" => "Allemagne"],
        [ "Nom" => "MATEL TEINTURERIE",  "Cp" => "11491", "Ville" => "Liège", "Pays" => "Belgique"],
        [ "Nom" => "MEDTEX Confection",  "Cp" => "82101", "Ville" => "Brussels", "Pays" => "Belgique"],
        [ "Nom" => "MGM",  "Cp" => "20618", "Ville" => "Bordeaux", "Pays" => "France"],
        [ "Nom" => "BFH",  "Cp" => "80941", "Ville" => "Lyon", "Pays" => "France"],
        [ "Nom" => "RONIMAN",  "Cp" => "27019", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "SOFAC",  "Cp" => "82823", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "SOMATEX",  "Cp" => "69809", "Ville" => "Berlin", "Pays" => "Allemagne"],
        [ "Nom" => "SOTAP CAROL",  "Cp" => "31311", "Ville" => "Montreal", "Pays" => "Canada"],
        [ "Nom" => "SOTUVET",  "Cp" => "21656", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "SPORTEX",  "Cp" => "82756", "Ville" => "Brussels", "Pays" => "Belgique"],
        [ "Nom" => "SYLVESTRE CONFECTION",  "Cp" => "79111", "Ville" => "Brussels", "Pays" => "Belgique"],
        [ "Nom" => "TAD",  "Cp" => "66443", "Ville" => "Brussels", "Pays" => "Belgique"],
        [ "Nom" => "TCI TRICOTAGE CIRCUL INDUST",  "Cp" => "60736", "Ville" => "Brussels", "Pays" => "Belgique"],
        [ "Nom" => "TEINTURERIE DE MATEL",  "Cp" => "91786", "Ville" => "Lille", "Pays" => "France"],
        [ "Nom" => "TEINTURERIE DRUHEN",  "Cp" => "57717", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "TEINTURERIE MOREUIL",  "Cp" => "85953", "Ville" => "Liège", "Pays" => "Belgique"],
        [ "Nom" => "THINON D. TRICOTAGE",  "Cp" => "24998", "Ville" => "Berlin", "Pays" => "Allemagne"],
        [ "Nom" => "TRICOTAGE DE CLARY",  "Cp" => "51956", "Ville" => "Nantes", "Pays" => "France"],
        [ "Nom" => "TRICOTAGE DE L'ENCLOS",  "Cp" => "24695", "Ville" => "Berlin", "Pays" => "Allemagne"],
        [ "Nom" => "TRICOTAGE TOULOUSAIN",  "Cp" => "66914", "Ville" => "Marseille", "Pays" => "France"],
        [ "Nom" => "TRICOTAGES DUCHAMP",  "Cp" => "85900", "Ville" => "Lille", "Pays" => "France"],
        [ "Nom" => "exapaq",  "Cp" => "25444", "Ville" => "Toronto", "Pays" => "Canada"],
        [ "Nom" => "MORY TEAM",  "Cp" => "50742", "Ville" => "Montreal", "Pays" => "Canada"],
        [ "Nom" => "JOYAU SCHENKER",  "Cp" => "12034", "Ville" => "Berlin", "Pays" => "Allemagne"],
        [ "Nom" => "MANUPAL",  "Cp" => "34480", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "BROD TUNIS SARL",  "Cp" => "25189", "Ville" => "Lille", "Pays" => "France"],
        [ "Nom" => "SVI",  "Cp" => "64933", "Ville" => "Liège", "Pays" => "Belgique"],
        [ "Nom" => "WORKWEAR",  "Cp" => "47248", "Ville" => "Brussels", "Pays" => "Belgique"],
        [ "Nom" => "JOD FACTORY",  "Cp" => "58924", "Ville" => "Munich", "Pays" => "Allemagne"],
        [ "Nom" => "SNS",  "Cp" => "77083", "Ville" => "Paris", "Pays" => "France"],
        [ "Nom" => "CHALETX",  "Cp" => "23198", "Ville" => "Bordeaux", "Pays" => "France"],
        [ "Nom" => "AJ GROUP",  "Cp" => "61679", "Ville" => "Montreal", "Pays" => "Canada"],
      ]);
    }
}